#!/usr/bin/env python3
"""Driver: execute the examples sync plan produced by plan.py.

Generates every KEEP_VERBATIM / REGEN / REMAP_REGEN / NEW / knowledge-new-tree
page via generate.render(), writing to <docs_root>/<slug>.mdx. Records
failures and docstring warnings to out/gen-log.json, and the DELETE slug list
to out/rm-list.txt (this script never deletes anything; review rm-list.txt and
remove those pages yourself). Run plan.py first: the plan is read from
out/sync-plan.json.

--check renders every page in memory and compares against what is on disk
without writing a single byte. Pages later modified by dedupe_titles.py or
apply_oneoffs.py will show as DIFFERS; the pipeline is only byte-stable
end-to-end (drive_sync -> dedupe_titles -> apply_oneoffs).

Usage:
    python scripts/examples_sync/drive_sync.py [--check]
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import generate as gen  # noqa: E402

REPO_ROOT = HERE.parents[1]
DOCS_ROOT = REPO_ROOT
AGNO_ROOT = Path(os.environ.get("AGNO_REPO") or REPO_ROOT / "agno")
COOKBOOK = AGNO_ROOT / "cookbook"
OUT_DIR = HERE / "out"
PLAN_PATH = OUT_DIR / "sync-plan.json"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="render in memory and diff against disk; write nothing")
    args = ap.parse_args()

    if not PLAN_PATH.is_file():
        raise SystemExit(f"error: {PLAN_PATH} not found; run plan.py first")
    plan = json.loads(PLAN_PATH.read_text())

    tasks: list[tuple[str, str, str]] = []  # (slug, cookbook-relative path, class)
    for e in plan["pages"]:
        cls = e["class"]
        if cls in ("KEEP_VERBATIM", "REGEN"):
            tasks.append((e["slug"], e["cookbook_path"], cls))
        elif cls == "REMAP_REGEN":
            tasks.append((e["slug"], e["new_cookbook_path"], cls))
    for e in plan["new_pages"]:
        tasks.append((e["slug"], e["cookbook_path"], "NEW"))
    for e in plan["knowledge_restructure"]["new_tree"]:
        tasks.append((e["slug"], e["cookbook_path"], "NEW_KNOWLEDGE"))

    # -----------------------------------------------------------------------
    # Safety assertions before writing a single byte
    # -----------------------------------------------------------------------
    slugs = [t[0] for t in tasks]
    assert all(s.startswith("examples/") for s in slugs), "slug outside examples/"
    dupes = [s for s, n in Counter(slugs).items() if n > 1]
    assert not dupes, f"duplicate slugs in task list: {dupes[:5]}"

    preserve = {e["slug"] for e in plan["pages"] if e["class"] == "PRESERVE_CURATED"}
    overlap_p = set(slugs) & preserve
    assert not overlap_p, f"task slugs collide with PRESERVE_CURATED: {sorted(overlap_p)[:5]}"

    # DELETE entries whose slug is regenerated by a NEW page from the SAME
    # cookbook source are overwrites, not deletions. Everything else must not
    # collide with a generation target.
    task_by_slug = {t[0]: t for t in tasks}
    rm_slugs: list[str] = []
    overwritten_orphans: list[str] = []
    for e in plan["pages"]:
        if e["class"] != "DELETE":
            continue
        t = task_by_slug.get(e["slug"])
        if t is None:
            rm_slugs.append(e["slug"])
        else:
            assert (
                e.get("subtype") == "orphan"
                and e.get("cookbook_path") == t[1]
            ), f"unexpected DELETE/generate collision: {e['slug']}"
            overwritten_orphans.append(e["slug"])
    if not args.check:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        (OUT_DIR / "rm-list.txt").write_text("\n".join(rm_slugs) + "\n")
    print(
        f"delete set: {len(rm_slugs)} to remove, "
        f"{len(overwritten_orphans)} orphan dupes overwritten in place",
        file=sys.stderr,
    )

    # No target may escape docs_root/examples (paranoia about '..' in slugs)
    for s in slugs:
        out = (DOCS_ROOT / f"{s}.mdx").resolve()
        assert str(out).startswith(str(DOCS_ROOT / "examples") + "/"), s

    print(f"tasks: {len(tasks)} ({Counter(t[2] for t in tasks)})", file=sys.stderr)

    # -----------------------------------------------------------------------
    # Generate
    # -----------------------------------------------------------------------
    written: dict[str, int] = Counter()
    failures: list[dict] = []
    warnings: list[dict] = []
    check_same: list[str] = []
    check_diff: list[str] = []
    check_missing: list[str] = []

    for slug, rel, cls in tasks:
        src_path = COOKBOOK / rel
        try:
            if not src_path.is_file():
                raise FileNotFoundError(f"cookbook file missing: {rel}")
            src = src_path.read_text(encoding="utf-8")
            buf = io.StringIO()
            with contextlib.redirect_stderr(buf):
                page = gen.render(src_path, f"cookbook/{rel}", src, AGNO_ROOT, slug=slug)
            if buf.getvalue().strip():
                warnings.append({"slug": slug, "class": cls, "warning": buf.getvalue().strip()})
            out = DOCS_ROOT / f"{slug}.mdx"
            if args.check:
                if not out.is_file():
                    check_missing.append(slug)
                elif out.read_text(encoding="utf-8") == page:
                    check_same.append(slug)
                else:
                    check_diff.append(slug)
            else:
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(page, encoding="utf-8")
                written[cls] += 1
        except Exception as exc:  # noqa: BLE001
            failures.append({"slug": slug, "class": cls, "source": rel, "error": f"{type(exc).__name__}: {exc}"})

    if args.check:
        print(json.dumps({
            "checked": len(tasks),
            "identical": len(check_same),
            "differs": len(check_diff),
            "missing_on_disk": len(check_missing),
            "failures": len(failures),
        }, indent=2))
        for s in check_diff[:40]:
            print("  DIFFERS:", s)
        if len(check_diff) > 40:
            print(f"  ... and {len(check_diff) - 40} more")
        for s in check_missing[:10]:
            print("  MISSING:", s)
        for f in failures[:10]:
            print("  FAIL:", f["slug"], "--", f["error"])
        return 1 if (failures or check_missing) else 0

    log = {
        "written": dict(written),
        "written_total": sum(written.values()),
        "failures": failures,
        "warnings_count": len(warnings),
        "warnings": warnings,
    }
    (OUT_DIR / "gen-log.json").write_text(json.dumps(log, indent=2))
    print(json.dumps({k: v for k, v in log.items() if k != "warnings"}, indent=2))
    print(f"warnings (placeholder descriptions etc.): {len(warnings)}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
